### ISSUE TITLE
It's a great honor to have you answer！

### ISSUE THREAD

**Issue by renguoyin123** [visualbuffer/copilot#2]
Hello, buddy, this project is really good, I am very interested in your research, I have three questions to ask: 
1, I would like to ask this program can run under what operating system, can run on the PC? 
2. What toolkits do you need to install before you can run the system?
 3. Can you tell me the setup steps and the running command line?

**Comment by ganeshmanikanta** [comment]
Hey, Hai...I would also like to thank him for this project. It was a great project.
For your questions, I think I will try to answer your questions.
1. I am running this code on Linux system, but I think you can also use windows PC with required packages. 
2. To be specific there are many libraries that are required to run this code starting with numpy, opencv,matplotlib .............keras, tensorflow.
The best way is to run this code in your python IDE (pychram, spider, Jupiter) and wait for the terminal to display an error about some missing packages or open each part of the code and check the import section for libraries used and install them
3. Setup is pretty clear, clone the repository and download the weights as mentioned in 'Download weights and code' as shown in Readme file.
Copy the code under 'usage example' into a fresh .py file, and replace the input and output file path with requirements (required path).

***Also I suggest you to go through the notebook or google colab explanation. They were  very clear. eg: like how to tune the input parameters. 
Also Algorithm for this code is explained in the medium website (link is provided in the Readme file).

Hope this will help and have a nice time.
