### ISSUE TITLE
Expected output on custom video

### ISSUE THREAD

**Issue by pythonmjs** [visualbuffer/copilot#7]
Hi, Thanks for the wonderful work. I really appreciate it. I have a few doubts about the parameters used while running on video.
1. how do you describe lane start? is it the same coordinate to start detecting the lane in the bird view image? 
2. which factors apart from frame's parameters do I need to change while running on the custom video?

Thanks!!

<img width="1680" alt="Screen Shot 2021-01-05 at 12 40 34 PM" src="https://user-images.githubusercontent.com/22041656/103696465-4137fc00-4f53-11eb-9f0d-850993d338fb.png">

**Comment by visualbuffer** [comment]
SELF VEHICLE OFFSET :Trim off from bottom edge video if ego vehicle covers part of the frame % of front view
